#version: "3.8"

services:
    traefik:
        image: traefik:latest
        container_name: traefik
        restart: unless-stopped
        depends_on:
            - authelia
            - tailscale
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /mnt/hc_data/server/traefik/config:/etc/traefik
            - /mnt/hc_data/server/traefik/certificates:/certificates
            - /mnt/hc_data/server/traefik/logs:/var/logs
            - /mnt/hc_data/server/tailscale/data:/var/lib/tailscale:ro
            - /mnt/hc_data/server/tailscale:/var/run/tailscale:ro
        ports:
            - 80:80
            - 443:443
            - 2222:2222
        networks:
            - traefik_net
            - monitoring_net
        command:
            - "--providers.docker"
            - "--providers.docker.exposedByDefault=false"
            - "--providers.docker.network=traefik_net"
            - "--entryPoints.web.address=:80"
            - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
            - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
            - "--entryPoints.websecure.address=:443"
            - "--entryPoints.ssh.address=:2222"
            - "--certificatesResolvers.prod.acme.storage=/certificates/acme.json"
            - "--certificatesResolvers.prod.acme.tlsChallenge=true"
            - "--certificatesResolvers.prod.acme.email=${TRAEFIK_ACME_EMAIL}"
            - "--certificatesResolvers.ts.tailscale=true"
            - "--accessLog"
            - "--accessLog.filePath=/var/logs/access.log"
            - "--metrics.prometheus"
            - "--api.dashboard=false"
        environment:
            - TZ=Europe/Berlin

    authelia:
        image: authelia/authelia:latest
        container_name: authelia
        restart: unless-stopped
        user: 1000:1000
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /mnt/hc_data/server/authelia/config:/config
        networks:
            - traefik_net
            - monitoring_net
        labels:
            - traefik.enable=true
            - traefik.http.routers.authelia.rule=Host(`${DOMAIN}`) && PathPrefix(`/auth`)
            - traefik.http.routers.authelia.entryPoints=websecure
            - traefik.http.routers.authelia.tls=true
            - traefik.http.routers.authelia.tls.certResolver=ts
            - traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https://${DOMAIN}/auth
            - traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true
            - traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups
            - traefik.http.middlewares.authelia_headers.headers.forceSTSHeader=true
            - traefik.http.middlewares.authelia_headers.headers.stsIncludeSubdomains=true
            - traefik.http.middlewares.authelia_headers.headers.stsPreload=false
            - traefik.http.middlewares.authelia_headers.headers.stsSeconds=31536000
            - traefik.http.middlewares.authelia_headers.headers.frameDeny=true
            - traefik.http.routers.authelia.middlewares=authelia@docker,authelia_headers
        environment:
            - X_AUTHELIA_CONFIG=/config/configuration.yml
            - X_AUTHELIA_CONFIG_FILTERS=template
            - DOMAIN=${DOMAIN}
            - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}

    tailscale:
        image: tailscale/tailscale:latest
        container_name: tailscale
        restart: unless-stopped
        hostname: ${TAILSCALE_HOSTNAME}
        network_mode: host
        cap_add:
            - net_admin
            - net_raw
        volumes:
            - /dev/net/tun:/dev/net/tun:ro
            - /mnt/hc_data/server/tailscale/data:/var/lib/tailscale
            - /mnt/hc_data/server/tailscale:/var/run/tailscale
        environment:
            - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_SOCKET=/var/run/tailscale/tailscaled.sock

networks:
    traefik_net:
        name: traefik_net
    monitoring_net:
        name: monitoring_net
