apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nextcloud
  name: database-pvc
  labels:
    app: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
