version: "3"

services:
    vscode:
        image: lscr.io/linuxserver/openvscode-server:latest
        container_name: vscode
        restart: unless-stopped
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /mnt/c_data/vscode/app:/config
        ports:
            - 4003:3000
        networks:
            - traefik_net
        labels:
            - traefik.enable=true
            - traefik.http.routers.vscode.rule=Host(`${VSCODE_DOMAIN}`)
            - traefik.http.routers.vscode.entrypoints=websecure
            - traefik.http.routers.vscode.tls=true
            - traefik.http.routers.vscode.tls.certresolver=prod
            - traefik.http.middlewares.vscode_headers.headers.forcestsheader=true
            - traefik.http.middlewares.vscode_headers.headers.stsincludesubdomains=true
            - traefik.http.middlewares.vscode_headers.headers.stspreload=false
            - traefik.http.middlewares.vscode_headers.headers.stsseconds=31536000
            - traefik.http.routers.vscode.middlewares=authelia@docker,vscode_headers
        environment:
            - TZ=Europe/Berlin

networks:
    traefik_net:
        external: true
