version: "3"

services:
    nextcloud:
        image: lscr.io/linuxserver/nextcloud:latest
        container_name: nextcloud
        restart: unless-stopped
        volumes:
            - /mnt/c_data/nextcloud/config:/config
            - /mnt/c_data/nextcloud/data:/data
        ports:
            - 4001:443
        networks:
            - traefik_web
        labels:
            - traefik.enable=true
            - traefik.http.routers.nextcloud.rule=Host(`nextcloud.domain`)
            - traefik.http.routers.nextcloud.entrypoints=websecure
            - traefik.http.routers.nextcloud.tls=true
            - traefik.http.routers.nextcloud.tls.certresolver=prod
            - traefik.http.middlewares.nextcloud_headers.headers.forcestsheader=true
            - traefik.http.middlewares.nextcloud_headers.headers.stsincludesubdomains=true
            - traefik.http.middlewares.nextcloud_headers.headers.stspreload=false
            - traefik.http.middlewares.nextcloud_headers.headers.stsseconds=31536000
            - traefik.http.routers.nextcloud.middlewares=authelia@docker,nextcloud_headers
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin

networks:
    traefik_web:
        external: true
