apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: jellyfin
  name: jellyfin-app-pvc
  labels:
    app: jellyfin

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
