version: "3"

services:
    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        restart: unless-stopped
        volumes:
            - type: bind
              source: /home/node3/disk/.docker/jellyfin/config
              target: /config
            - type: bind
              source: /home/node3/disk/media/movies
              target: /data/movies
              read_only: true
            - type: bind
              source: /home/node3/disk/media/series
              target: /data/series
              read_only: true
            - type: bind
              source: /home/node3/disk/media/videos
              target: /data/videos
              read_only: true
            - type: bind
              source: /home/node3/disk/media/other
              target: /data/other
              read_only: true
        ports:
            - 8096:8096
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
