apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: opencloud
  name: opencloud-app-pvc
  labels:
    app: opencloud

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
