version: "3"

services:
    authelia:
        image: authelia/authelia:latest
        container_name: authelia
        restart: unless-stopped
        volumes:
            - /etc/authelia:/config
        ports:
            - 9091:9091
        networks:
            - traefik_web
        labels:
            - traefik.enable=true
            - traefik.http.routers.authelia.rule=Host(`auth.domain`)
            - traefik.http.routers.authelia.entrypoints=websecure
            - traefik.http.routers.authelia.tls=true
            - traefik.http.routers.heimdall.tls.certresolver=prod
            - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify
            - traefik.http.middlewares.authelia.forwardauth.trustforwardheader=true
            - traefik.http.middlewares.authelia.forwardauth.authresponseheaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
        environment:
            - TZ=Europe/Berlin

networks:
    traefik_web:
        external: true
