#version: "3.8"

services:
    jellyfin:
        image: jellyfin/jellyfin:latest
        container_name: jellyfin
        restart: unless-stopped
        user: 1000:1000
        volumes:
            - /mnt/c_data/jellyfin/config:/config
            - /mnt/c_data/jellyfin/cache:/cache
            - /mnt/extern/media/movies:/data/movies:ro
            - /mnt/extern/media/shows:/data/shows:ro
            - /mnt/extern/media/videos:/data/videos:ro
            - /mnt/extern/media/photos:/data/photos:ro
            - /mnt/extern/media/other:/data/other:ro
        devices:
            - /dev/dri:/dev/dri
            - /dev/dri/card0:/dev/dri/card0
            - /dev/dri/card1:/dev/dri/card1
            - /dev/dri/renderD128:/dev/dri/renderD128
        ports:
            - 18096:8096
        networks:
            - traefik_net
        labels:
            - traefik.enable=true
            - traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_DOMAIN}`)
            - traefik.http.routers.jellyfin.entryPoints=websecure
            - traefik.http.routers.jellyfin.tls=true
            - traefik.http.routers.jellyfin.tls.certResolver=prod
            - traefik.http.middlewares.jellyfin_headers.headers.forceSTSHeader=true
            - traefik.http.middlewares.jellyfin_headers.headers.stsIncludeSubdomains=true
            - traefik.http.middlewares.jellyfin_headers.headers.stsPreload=false
            - traefik.http.middlewares.jellyfin_headers.headers.stsSeconds=31536000
            - traefik.http.routers.jellyfin.middlewares=authelia@docker,jellyfin_headers
        environment:
            - TZ=Europe/Berlin

networks:
    traefik_net:
        external: true
