theme: auto

default_2fa_method: totp

server:
    address: "tcp://:9091/auth"

telemetry:
    metrics:
        enabled: true
        address: "tcp://:9959/metrics"

access_control:
    default_policy: deny
    rules:
        - domain: {{ env "DOMAIN" }}
          resources:
              - "^/auth([/?].*)?$"
          policy: bypass
        - domain: {{ env "DOMAIN" }}
          resources:
              - "^/grafana([/?].*)?$"
          policy: two_factor
        - domain: {{ env "DOMAIN" }}
          resources:
              - "^/nextcloud([/?].*)?$"
          policy: bypass

authentication_backend:
    file:
        path: /config/users.yml
        password:
            algorithm: argon2id
            iterations: 2
            memory: 1024
            parallelism: 4
            key_length: 32
            salt_length: 16
        watch: true
    password_reset:
        disable: true

storage:
    local:
        path: /config/db.sqlite3
    encryption_key: secret

session:
    name: authelia_session
    secret: {{ env "AUTHELIA_SESSION_SECRET" }}
    expiration: 3600
    inactivity: 300
    cookies:
        - domain: {{ env "DOMAIN" }}
          authelia_url: https://{{ env "DOMAIN" }}/auth

regulation:
    max_retries: 3
    find_time: 5m
    ban_time: 24h

totp:
    disable: false
    issuer: {{ env "DOMAIN" }}

webauthn:
    disable: true

duo_api:
    disable: true

notifier:
    filesystem:
        filename: /config/notification

log:
    level: info
