version: "3"

services:
    nextcloud:
        image: lscr.io/linuxserver/nextcloud:latest
        container_name: nextcloud
        restart: unless-stopped
        volumes:
            - type: bind
              source: /home/node2/docs/nextcloud/config
              target: /config
            - type: bind
              source: /home/node2/docs/nextcloud/data
              target: /data
        ports:
            - 443:443
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
