version: "3"

services:
    vaultwarden:
        image: vaultwarden/server:latest
        container_name: vaultwarden
        restart: unless-stopped
        volumes:
            - type: bind
              source: /mnt/c_data/vaultwarden/data
              target: /data
        ports:
            - 1080:80
        environment:
            - ADMIN_TOKEN=secret
            - DOMAIN=https://vaultwarden.domain
