version: "3"

services:
    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        restart: unless-stopped
        volumes:
            - /etc/jellyfin:/config
            - /mnt/extern_disk/media/movies:/data/movies:ro
            - /mnt/extern_disk/media/series:/data/series:ro
            - /mnt/extern_disk/media/videos:/data/videos:ro
            - /mnt/extern_disk/media/photos:/data/photos:ro
            - /mnt/extern_disk/media/other:/data/other:ro
        ports:
            - 4003:8096
        networks:
            - traefik_web
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin

networks:
    traefik_web:
        external: true
