version: "3"

services:
    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        restart: unless-stopped
        volumes:
            - /mnt/c_data/jellyfin/config:/config
            - /mnt/extern_disk/media/movies:/data/movies:ro
            - /mnt/extern_disk/media/series:/data/series:ro
            - /mnt/extern_disk/media/videos:/data/videos:ro
            - /mnt/extern_disk/media/photos:/data/photos:ro
            - /mnt/extern_disk/media/other:/data/other:ro
        ports:
            - 4004:8096
        networks:
            - traefik_net
        labels:
            - traefik.enable=false
            - traefik.http.routers.jellyfin.rule=Host(`jellyfin.domain`)
            - traefik.http.routers.jellyfin.entrypoints=websecure
            - traefik.http.routers.jellyfin.tls=true
            - traefik.http.routers.jellyfin.tls.certresolver=prod
            - traefik.http.middlewares.jellyfin_headers.headers.forcestsheader=true
            - traefik.http.middlewares.jellyfin_headers.headers.stsincludesubdomains=true
            - traefik.http.middlewares.jellyfin_headers.headers.stspreload=false
            - traefik.http.middlewares.jellyfin_headers.headers.stsseconds=31536000
            - traefik.http.routers.jellyfin.middlewares=authelia@docker,jellyfin_headers
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin

networks:
    traefik_net:
        external: true
