#version: "3.8"

services:
    collabora:
        image: collabora/code:24.04.2.1.1
        container_name: collabora
        restart: unless-stopped
        networks:
            - traefik_net
        labels:
            - traefik.enable=true
            - traefik.http.routers.collabora.rule=Host(`${COLLABORA_DOMAIN}`)
            - traefik.http.routers.collabora.entryPoints=websecure
            - traefik.http.routers.collabora.tls=true
            - traefik.http.routers.collabora.tls.certResolver=prod
            - traefik.http.middlewares.collabora_headers.headers.forceSTSHeader=true
            - traefik.http.middlewares.collabora_headers.headers.stsIncludeSubdomains=true
            - traefik.http.middlewares.collabora_headers.headers.stsPreload=false
            - traefik.http.middlewares.collabora_headers.headers.stsSeconds=31536000
            - traefik.http.routers.collabora.middlewares=authelia@docker,collabora_headers
        environment:
            - extra_params=--o:ssl.enable=false --o:ssl.termination=true
            - username=collabora
            - password=${COLLABORA_PASSWORD}

networks:
    traefik_net:
        external: true
