global:
    scrape_interval: 5s
    evaluation_interval: 5s

scrape_configs:
    - job_name: "traefik"
      static_configs:
          - targets: ["traefik:8080"]

    - job_name: "authelia"
      static_configs:
          - targets: ["authelia:9959"]

    - job_name: "prometheus"
      static_configs:
          - targets: ["prometheus:9090"]

    - job_name: "prom-node-exporter"
      static_configs:
          - targets: ["prom-node-exporter:9100"]

    - job_name: "cadvisor"
      static_configs:
          - targets: ["cadvisor:8080"]
