version: "3"

services:
    traefik:
        image: traefik:v2.9.9
        container_name: traefik
        restart: unless-stopped
        command: --providers.docker
        volumes:
            - /etc/traefik:/etc/traefik
            - /etc/traefik/traefik-ssl-certs:/ssl-certs
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - 80:80
            - 443:443
            - 8080:8080

    authelia:
        image: authelia/authelia:latest
        container_name: authelia
        restart: unless-stopped
        volumes:
            - /etc/authelia:/config
        ports:
            - 9091:9091
        environment:
            - TZ=Europe/Berlin

    heimdall:
        image: lscr.io/linuxserver/heimdall:latest
        container_name: heimdall
        restart: unless-stopped
        volumes:
            - /etc/heimdall:/config
        ports:
            - 1443:443
        labels:
            - traefik.http.routers.heimdall.rule=Host(`heimdall.domain`)
            - traefik.http.routers.adminer.tls=true
            - traefik.http.routers.adminer.tls.certresolver=production
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
