version: "3"

services:
    traefik:
        image: traefik:latest
        container_name: traefik
        restart: unless-stopped
        volumes:
            - traefik:/etc/traefik
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - 80:80
            - 443:443
            - 8080:8080

    authelia:
        image: authelia/authelia:latest
        container_name: authelia
        restart: unless-stopped
        volumes:
            - authelia:/config
        ports:
            - 9091:9091
        environment:
            - TZ=Europe/Berlin

    heimdall:
        image: lscr.io/linuxserver/heimdall:latest
        container_name: heimdall
        restart: unless-stopped
        volumes:
            - heimdall:/config
        ports:
            - 1443:443
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin

volumes:
    traefik:
        external: false
    authelia:
        external: false
    heimdall:
        external: false
