version: "3"

services:
    traefik:
        image: traefik:latest
        container_name: traefik
        restart: unless-stopped
        command:
            - "--providers.docker"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.docker.network=traefik_web"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.prod.acme.storage=/letsencrypt/acme.json"
            - "--certificatesresolvers.prod.acme.tlschallenge=true"
            - "--certificatesresolvers.prod.acme.email=email"
        volumes:
            - /etc/traefik:/etc/traefik
            - /etc/traefik/letsencrypt:/letsencrypt
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - 80:80
            - 443:443
        networks:
            - web

networks:
    web:
        name: traefik_web
