users:
    admin:
        password: $argon2id$v=19$m=65536,t=12,p=4$eVA3VFRLWjV4b0ZLQURheA$U+bgJi5CD2S7Qe7xZHWZVfECpjKXWxCv6DaYpfE2VGs # 1234
        displayname: admin
        email: invalid
        groups:
            - admins
            - dev
        disabled: true
    luwe:
        password: $argon2id$v=19$m=65536,t=12,p=4$ZTJqTEtDR2htVW1jZHBCcA$XXrTf6mqvh3ssz5NRu7O3z7sQXIY1L09I02PhJP+gGQ # 5678
        displayname: luwe
        email: invalid
        groups: []
        disabled: false
