users:
    admin:
        password: $argon2id$v=19$m=2097152,t=4,p=4$5NzN0Amj1ChmSmiCFDxWZg$5J46DcvQqy69wCh9zs+XlrLroRW7iOmxTkoMt2JsQ/w # admin
        displayname: admin
        email: invalid
        groups:
            - admins
            - dev
        disabled: true
    guest:
        password: $argon2id$v=19$m=2097152,t=4,p=4$izJ9TUT6c0hkV2zbm4bO/A$5vl0jSm2SbllaOxVwVvxeoUqwEzFSNB9anaHxmHkXjI # guest
        displayname: guest
        email: invalid
        groups: []
        disabled: false
    luwe:
        password: $argon2id$v=19$m=2097152,t=4,p=4$YcBspet5Rc/5dIoQtu0qow$6GPDgiwfnFJid4NAcb5kZgS2WQ8+mOm9FXOMs/91I08 # luwe
        displayname: luwe
        email: invalid
        groups: []
        disabled: false
