users:
    admin:
        password: $argon2id$v=19$m=65536,t=4,p=4$WGgwQU1UUGZ4dFE3VnpVYQ$uDuUDFRijjiVX+dcyDuayyHAUNgUtnrTKGGHpT9NjkM # 1234
        displayname: admin
        email: invalid
        groups:
            - admins
            - dev
        disabled: false
    luwe:
        password: $argon2id$v=19$m=65536,t=4,p=4$WGgwQU1UUGZ4dFE3VnpVYQ$uDuUDFRijjiVX+dcyDuayyHAUNgUtnrTKGGHpT9NjkM # 1234
        displayname: luwe
        email: invalid
        groups: []
        disabled: false
