version: "3"

services:
    heimdall:
        image: lscr.io/linuxserver/heimdall:latest
        container_name: heimdall
        restart: unless-stopped
        volumes:
            - /mnt/c_data/heimdall/config:/config
        ports:
            - 4000:443
        networks:
            - traefik_net
        labels:
            - traefik.enable=true
            - traefik.http.routers.heimdall.rule=Host(`${HEIMDALL_DOMAIN}`)
            - traefik.http.routers.heimdall.entrypoints=websecure
            - traefik.http.routers.heimdall.tls=true
            - traefik.http.routers.heimdall.tls.certresolver=prod
            - traefik.http.middlewares.heimdall_headers.headers.forcestsheader=true
            - traefik.http.middlewares.heimdall_headers.headers.stsincludesubdomains=true
            - traefik.http.middlewares.heimdall_headers.headers.stspreload=false
            - traefik.http.middlewares.heimdall_headers.headers.stsseconds=31536000
            - traefik.http.routers.heimdall.middlewares=authelia@docker,heimdall_headers
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin

networks:
    traefik_net:
        external: true
