apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: vaultwarden
  name: vaultwarden-app-pvc
  labels:
    app: vaultwarden

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
