apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: grafana
  name: grafana-app-pvc
  labels:
    app: grafana-app

spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
