apiVersion: v1

kind: Service

metadata:
  namespace: grafana
  name: grafana-app-service
  labels:
    app: grafana-app

spec:
  selector:
    app: grafana-app
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
