theme: auto

default_2fa_method: totp

server:
    address: "tcp://:9091/auth"

access_control:
    default_policy: deny
    rules:
        - domain: domain
          resources:
              - "^/auth([/?].*)?$"
          policy: bypass
        - domain: domain
          resources:
              - "^/grafana([/?].*)?$"
          policy: two_factor

authentication_backend:
    refresh_interval: 5m
    file:
        path: /config/users_database.yml
        password:
            algorithm: argon2id
            iterations: 2
            memory: 1024
            parallelism: 4
            key_length: 32
            salt_length: 16
    password_reset:
        disable: true

session:
    name: authelia_session
    secret: secret
    expiration: 3600
    inactivity: 300
    cookies:
        - domain: domain
          authelia_url: "https://domain/auth"

regulation:
    max_retries: 2
    find_time: 5m
    ban_time: 24h

totp:
    disable: false
    issuer: domain

webauthn:
    disable: true

storage:
    local:
        path: /config/db.sqlite3
    encryption_key: secret

notifier:
    filesystem:
        filename: /config/notification

log:
    level: info
