apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: keycloak
  name: keycloak-database-pvc
  labels:
    app: keycloak-database

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
