services:
    grafana:
        image: grafana/grafana:12.2.0
        container_name: grafana
        restart: unless-stopped
        user: 1000:1000
        depends_on:
            - prometheus
        volumes:
            - /mnt/homecloud/data/monitoring/grafana/app:/var/lib/grafana
        networks:
            - monitoring_net
            - traefik_net
        labels:
            - traefik.enable=true
            - traefik.http.routers.grafana.rule=Host(`${DOMAIN}`) && PathRegexp(`^/grafana([/?].*)?$`)
            - traefik.http.routers.grafana.entryPoints=websecure
            - traefik.http.routers.grafana.tls=true
            - traefik.http.routers.grafana.tls.certResolver=ts
            - traefik.http.middlewares.grafana_headers.headers.forceSTSHeader=true
            - traefik.http.middlewares.grafana_headers.headers.stsIncludeSubdomains=true
            - traefik.http.middlewares.grafana_headers.headers.stsPreload=false
            - traefik.http.middlewares.grafana_headers.headers.stsSeconds=31536000
            - traefik.http.routers.grafana.middlewares=authelia@docker,grafana_headers
            - traefik.http.services.grafana.loadBalancer.server.port=3000
        environment:
            - GF_SERVER_DOMAIN=${DOMAIN}
            - GF_SERVER_ROOT_URL=https://${DOMAIN}/grafana
            - GF_SERVER_SERVE_FROM_SUB_PATH=true

    prometheus:
        image: prom/prometheus:v3.6.0
        container_name: prometheus
        restart: unless-stopped
        user: 1000:1000
        volumes:
            - /mnt/homecloud/data/monitoring/prometheus/config:/etc/prometheus
            - /mnt/homecloud/data/monitoring/prometheus/database:/prometheus
        networks:
            - monitoring_net
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time=56d"

    prometheus-node-exporter:
        image: prom/node-exporter:v1.9.1
        container_name: prometheus-node-exporter
        restart: unless-stopped
        volumes:
            - /:/host/rootfs:ro
            - /proc:/host/procfs:ro
            - /sys:/host/sysfs:ro
        networks:
            - monitoring_net
        command:
            - "--path.rootfs=/host/rootfs"
            - "--path.procfs=/host/procfs"
            - "--path.sysfs=/host/sysfs"
            - "--collector.processes"

networks:
    monitoring_net:
        external: true
    traefik_net:
        external: true
